name: ⚡ Upload MP4 Only to PixelDrain

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent の URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  upload-mp4-to-pixeldrain:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 curl jq

      - name: Download via aria2c
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      - name: Upload each MP4 to PixelDrain
        id: upload
        run: |
          declare -a uploaded

          find content -type f -iname '*.mp4' | while IFS= read -r file; do
            echo "📤 Uploading: $file"

            response=$(curl -s -X POST -F "file=@$file" https://pixeldrain.com/api/file)
            echo "⚙️ Response: $response"

            id=$(echo "$response" | jq -r '.id')
            if [ -n "$id" ] && [ "$id" != "null" ]; then
              url="https://pixeldrain.com/u/$id"
              echo "✅ Success: $url"
              uploaded+=("$file: $url")
            else
              echo "❌ Upload failed for $file"
              exit 1
            fi
          done

          echo "results<<EOF" >> $GITHUB_OUTPUT
          for entry in "${uploaded[@]}"; do
            echo "$entry"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show uploaded MP4 URLs
        run: |
          echo "===== MP4 Upload Results ====="
          echo "${{ steps.upload.outputs.results }}"
