name: ⚡ Download and Upload MP4

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent の URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト（コミット権限は不要になりましたが残しています）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. 必要ツールのインストール
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 python3-pip

      # 3. Torrent から MP4 をダウンロード
      - name: Download via aria2c
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      # 4. ダウンロードした MP4 を GigaFile便 にアップロードし、URL を表示
      - name: Upload MP4 to GigaFile便 and show URLs
        run: |
          pip3 install --upgrade gigafile
          echo "=== Uploaded URLs ==="
          for f in content/*.mp4; do
            echo "📤 Uploading $f …"
            # GigaFile CLI が返す URL をキャプチャ
            url=$(gfile upload "$f")
            echo "→ $url"
          done
