name: ⚡ Torrent 内の MP4 のみ GigaFile便 にアップロード

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent の URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  upload-mp4-only:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 curl python3-pip

      - name: Download via aria2c (max parallel)
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      - name: Install gfile CLI for GigaFile便
        run: |
          pip3 install --no-cache-dir git+https://github.com/Sraq-Zit/gfile.git

      - name: Upload each MP4 to GigaFile便
        id: upload
        run: |
          declare -a uploaded
          # .torrent ファイルは除外し、MP4 だけを探す
          while IFS= read -r file; do
            echo "Uploading: $file"
            url=$(gfile upload "$file")   # 
            echo " → $url"
            uploaded+=("$file: $url")
          done < <(find content -type f \( -iname '*.mp4' \))

          # 結果をまとめて出力変数へ
          echo "results<<EOF" >> $GITHUB_OUTPUT
          for entry in "${uploaded[@]}"; do
            echo "$entry"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show uploaded MP4 URLs
        run: |
          echo "===== MP4 アップロード結果 ====="
          echo "${{ steps.upload.outputs.results }}"
