name: ⚡ Super Fast Torrent Download & Upload to GigaFile便

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent の URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  turbo:
    runs-on: ubuntu-latest

    steps:
      - name: Install minimal tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 pigz curl python3-pip

      - name: Download via aria2c (max parallel)
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      - name: Parallel compress with pigz + tar
        run: |
          tar cf - -C content . | pigz -p $(nproc) > download.tar.gz

      - name: Install gfile CLI for GigaFile便
        run: |
          # gfile: Pythonモジュール兼CLI。uploadコマンドでギガファイル便へ送信可能
          pip3 install --no-cache-dir git+https://github.com/Sraq-Zit/gfile.git

      - name: Upload to GigaFile便
        id: upload
        run: |
          # gfile upload が返す URL をそのままキャプチャ
          URL=$(gfile upload download.tar.gz)
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Reveal final GigaFile便 URL
        run: |
          echo "👉 GigaFile便 のダウンロードページはこちら: ${{ steps.upload.outputs.url }}"
