name: ⚡ Upload MP4 Only to GigaFile便

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent の URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  upload-mp4-to-gigafile:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 curl jq python3-pip

      - name: Download via aria2c
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      - name: Install gigafile CLI
        run: |
          python3 -m pip install --upgrade pip
          pip install gigafile

      - name: Upload each MP4 to GigaFile便
        id: upload
        run: |
          declare -a uploaded

          find content -type f -iname '*.mp4' | while IFS= read -r file; do
            echo "📤 Uploading: $file"
            # --mute オプションで URL のみが出力されます
            url=$(gfile upload --mute "$file")
            if [[ "$url" =~ ^https?:// ]]; then
              echo "✅ Success: $url"
              uploaded+=("$file: $url")
            else
              echo "❌ Upload failed for $file"
              exit 1
            fi
          done

          # 結果を GitHub Actions の出力変数に設定
          echo "results<<EOF" >> $GITHUB_OUTPUT
          for entry in "${uploaded[@]}"; do
            echo "$entry"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show uploaded MP4 URLs
        run: |
          echo "===== MP4 Upload Results ====="
          echo "${{ steps.upload.outputs.results }}"
