name: ⚡ Torrent 内ファイルを直接 GigaFile便 にアップロード

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent の URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  upload-all:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 curl python3-pip

      - name: Download via aria2c (max parallel)
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      - name: Install gfile CLI for GigaFile便
        run: |
          pip3 install --no-cache-dir git+https://github.com/Sraq-Zit/gfile.git

      - name: Upload each file to GigaFile便
        id: upload
        run: |
          # content/ 以下の全ファイルを再帰検索してアップロード
          declare -a uploaded
          while IFS= read -r file; do
            echo "Uploading: $file"
            url=$(gfile upload "$file")  #  [oai_citation_attribution:0‡GitHub](https://github.com/Sraq-Zit/gfile)
            echo " → $url"
            uploaded+=("$file: $url")
          done < <(find content -type f)

          # 結果を改行区切りの文字列として出力変数にセット
          echo "results<<EOF" >> $GITHUB_OUTPUT
          for entry in "${uploaded[@]}"; do
            echo "$entry"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show all uploaded URLs
        run: |
          echo "===== アップロード結果 ====="
          echo "${{ steps.upload.outputs.results }}"
