name: ⚡ Download, Compress MP4, and Push to Repo

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent の URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  download-compress-push:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト（コミット権限付き）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # GITHUB_TOKEN を維持
          fetch-depth: 0              # full history

      # 2. 必要ツールのインストール
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 ffmpeg

      # 3. Torrent から MP4 をダウンロード
      - name: Download via aria2c
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      # 4. MP4 を最大圧縮
      - name: Compress MP4 files
        run: |
          mkdir compressed
          find content -type f -iname '*.mp4' | while IFS= read -r file; do
            echo "🔧 Compressing: $file"
            filename=$(basename "$file")
            # H.264でCRF35、very slowプリセット、AAC 128kbps で圧縮
            ffmpeg -y -i "$file" \
              -c:v libx264 -preset veryslow -crf 35 \
              -c:a aac -b:a 128k \
              "compressed/$filename"
          done

      # 5. 圧縮後ファイルをコミット＆プッシュ
      - name: Commit and push compressed files
        run: |
          cd $GITHUB_WORKSPACE
          # Gitユーザー設定
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 変更チェック
          if git diff --quiet --exit-code compressed/; then
            echo "No changes in compressed/ – skipping commit."
          else
            git add compressed/
            git commit -m "Add compressed MP4 files"
            git push
          fi
