name: ⚡ Upload MP4 Only to transfer.sh

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent ファイルの URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  upload-mp4-to-transfersh:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 curl

      - name: Download via aria2c (max parallel)
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      - name: Upload each MP4 to transfer.sh with retry logic
        id: upload
        run: |
          declare -a uploaded
          MAX_RETRIES=5
          SLEEP_INTERVAL=10

          # content/ 以下の MP4 ファイルだけを列挙
          find content -type f -iname '*.mp4' | while read -r file; do
            echo "📤 Uploading: $file"

            attempt=1
            success=false
            until [ $attempt -gt $MAX_RETRIES ]; do
              # transfer.sh は HTTP PUT で受け付け。返却はアップロード先の URL  [oai_citation_attribution:0‡GitHub](https://github.com/dutchcoders/transfer.sh/blob/main/examples.md?utm_source=chatgpt.com) [oai_citation_attribution:1‡LFCS認定準備eBook](https://www.tecmint.com/file-sharing-from-linux-commandline/?utm_source=chatgpt.com)
              if url=$(curl --fail --silent --show-error --upload-file "$file" https://transfer.sh/$(basename "$file")); then
                echo "✅ Success: $url"
                success=true
                break
              else
                echo "⚠️  Attempt $attempt/$MAX_RETRIES failed—retrying in ${SLEEP_INTERVAL}s..."
                attempt=$((attempt+1))
                sleep $SLEEP_INTERVAL
              fi
            done

            if [ "$success" = false ]; then
              echo "❌ Failed to upload $file after $MAX_RETRIES attempts" >&2
              exit 1
            fi

            uploaded+=("$file: $url")
          done

          # 結果を出力変数にまとめる
          echo "results<<EOF" >> $GITHUB_OUTPUT
          for entry in "${uploaded[@]}"; do
            echo "$entry"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show uploaded MP4 URLs
        run: |
          echo "===== MP4 Upload Results ====="
          echo "${{ steps.upload.outputs.results }}"
