name: ⚡ Upload MP4 Only to file.io (Fixed URL Extraction)

on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'ダウンロードする .torrent ファイルの URL'
        required: true
        default: 'https://sukebei.nyaa.si/download/3957463.torrent'

jobs:
  upload-mp4-to-fileio:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq aria2 curl jq

      - name: Download via aria2c (max parallel)
        run: |
          mkdir content
          aria2c \
            --dir=content \
            --seed-time=0 \
            --split=16 \
            --max-connection-per-server=16 \
            --max-concurrent-downloads=4 \
            --min-split-size=1M \
            --retry-wait=5 \
            --timeout=60 \
            --summary-interval=1 \
            "${{ github.event.inputs.torrent_url }}"

      - name: Upload each MP4 to file.io with robust URL parsing
        id: upload
        run: |
          declare -a uploaded
          MAX_RETRIES=5
          SLEEP_INTERVAL=10

          find content -type f -iname '*.mp4' | while IFS= read -r file; do
            echo "📤 Uploading: $file"
            attempt=1
            success=false

            until [ $attempt -gt $MAX_RETRIES ]; do
              # アップロード
              response=$(curl -s -F file=@"$file" https://file.io?expires=14d)
              echo "⚙️ Response JSON: $response"

              # まず link を取得
              link=$(echo "$response" | jq -r '.link // empty')
              if [ -z "$link" ] || [ "$link" = "null" ]; then
                # link が空 or null なら id or key から URL を構築
                id=$(echo "$response" | jq -r '.id // .key // empty')
                if [ -n "$id" ]; then
                  url="https://file.io/$id"
                else
                  url=""
                fi
              else
                url="$link"
              fi

              if [ -n "$url" ]; then
                echo "✅ Success: $url"
                success=true
                break
              else
                echo "⚠️ Attempt $attempt/$MAX_RETRIES failed to extract URL, retrying in ${SLEEP_INTERVAL}s..."
                attempt=$((attempt+1))
                sleep $SLEEP_INTERVAL
              fi
            done

            if [ "$success" = false ]; then
              echo "❌ Failed to upload $file after $MAX_RETRIES attempts" >&2
              exit 1
            fi

            uploaded+=("$file: $url")
          done

          # 結果を出力変数にまとめる
          echo "results<<EOF" >> $GITHUB_OUTPUT
          for entry in "${uploaded[@]}"; do
            echo "$entry"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show uploaded MP4 URLs
        run: |
          echo "===== MP4 Upload Results ====="
          echo "${{ steps.upload.outputs.results }}"
